/// Describes project in which the AWS resource was utilized
table DimProject
	lineageTag: 89c9c6dd-306d-4c5f-ab39-93a07713844f

	column project_key
		dataType: int64
		formatString: 0
		lineageTag: a1133024-5def-4516-b6cd-f5228f9adb3d
		summarizeBy: none
		sourceColumn: project_key

		annotation SummarizationSetBy = Automatic

	column tag_project
		dataType: string
		lineageTag: 42860df9-1b95-4e0f-9212-102b9dea99d1
		summarizeBy: none
		sourceColumn: tag_project

		annotation SummarizationSetBy = Automatic

	partition DimProject = m
		mode: import
		source =
				let
				    Source = Cloudcost_CUR,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"tag_project"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Sorted Rows" = Table.Sort(#"Removed Duplicates",{{"tag_project", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 0, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "tag_project"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "project_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

